/* 句块训练库：由早期平台的可复用商务表达经筛选、改写后迁入。
 * 只保留适用于双语接待、品牌讲述、会展导览的标准表达；不包含未经核验的产品承诺。
 */
window.PHRASE_BANK = [
  {en:"The short answer is…",zh:"简短回答是……",tag:"结论先行",use:"先给对方方向，再补充理由或边界。",example:"The short answer is yes, for standard workflows."},
  {en:"At a high level,…",zh:"从总体层面看……",tag:"公司与业务介绍",use:"用于先搭框架，避免一开始陷入细节。",example:"At a high level, we combine cloud, AI and industry expertise."},
  {en:"In practical terms,…",zh:"落实到实际应用上……",tag:"解释技术",use:"把概念转到业务动作或工作流。",example:"In practical terms, the system helps teams handle a defined workflow."},
  {en:"The key point is that…",zh:"关键在于……",tag:"强调重点",use:"在信息很多时指出最重要的一点。",example:"The key point is that the solution must create measurable value."},
  {en:"For example,…",zh:"例如……",tag:"举例",use:"在抽象说明后给一个具体、可核验的例子。",example:"For example, a team may start with one customer-service workflow."},
  {en:"A concrete use case is…",zh:"一个具体用例是……",tag:"案例讲解",use:"把讨论从泛泛而谈拉回一个明确场景。",example:"A concrete use case is drafting a first response for support agents."},
  {en:"What this means for your team is…",zh:"这对您的团队意味着……",tag:"客户价值",use:"把产品能力翻译成听众关心的影响。",example:"What this means for your team is a clearer and more consistent process."},
  {en:"We would start by understanding…",zh:"我们会先了解……",tag:"需求澄清",use:"用于说明合作或演示的正确起点。",example:"We would start by understanding the business problem and success criteria."},
  {en:"What would success look like for you?",zh:"对您而言，成功会是什么样？",tag:"需求提问",use:"用开放问题确认客户真正想达成的结果。",example:"What would success look like for you after a three-month pilot?"},
  {en:"Could you tell me more about…?",zh:"您能否再多介绍一下……？",tag:"澄清提问",use:"听不清背景或条件时，礼貌地追问。",example:"Could you tell me more about your current workflow?"},
  {en:"If I understood correctly,…",zh:"如果我理解正确的话……",tag:"复述确认",use:"复述对方意思，减少误解。",example:"If I understood correctly, integration time is your main concern."},
  {en:"Do you mean A or B?",zh:"您指的是 A 还是 B？",tag:"精确澄清",use:"用选项把模糊问题变得可回答。",example:"Do you mean the cloud deployment or an on-premises setup?"},
  {en:"Let me walk you through…",zh:"我带您逐步看一下……",tag:"导览与演示",use:"进入展项、流程或页面讲解前的自然过渡。",example:"Let me walk you through the main steps of the workflow."},
  {en:"Let me show you a brief example.",zh:"我给您看一个简短的例子。",tag:"演示引导",use:"把口头介绍转入案例或演示。",example:"Let me show you a brief example from a typical business scenario."},
  {en:"There are three points to highlight.",zh:"有三点值得重点说明。",tag:"结构表达",use:"让较长回答有清晰路线。",example:"There are three points to highlight: value, implementation and governance."},
  {en:"First,… Second,… Finally,…",zh:"第一……第二……最后……",tag:"结构表达",use:"按顺序说明，方便外宾跟上。",example:"First, we define the scope. Second, we test it. Finally, we review the outcome."},
  {en:"That is a fair question.",zh:"这是一个很合理的问题。",tag:"现场问答",use:"先接住提问，再进入回答；不等同于承诺。",example:"That is a fair question. Let me explain what we can confirm today."},
  {en:"That is a fair concern.",zh:"这是一个合理的顾虑。",tag:"异议回应",use:"回应安全、成本、集成等顾虑时先表示理解。",example:"That is a fair concern, especially when the workflow involves sensitive data."},
  {en:"I do not want to guess on that.",zh:"关于这一点，我不想凭猜测回答。",tag:"不确定性处理",use:"对数字、价格、合规或未确认细节，先设边界。",example:"I do not want to guess on that; I will verify it with the relevant team."},
  {en:"Let me verify the exact detail and get back to you.",zh:"我核实准确细节后再回复您。",tag:"不确定性处理",use:"把“不确定”转为明确的后续动作。",example:"Let me verify the exact detail and get back to you after the session."},
  {en:"What I can confirm at this point is…",zh:"目前我可以确认的是……",tag:"边界与转场",use:"明确已知范围，再讲能可靠说明的部分。",example:"What I can confirm at this point is the general implementation approach."},
  {en:"That would need to be assessed for your specific case.",zh:"这需要结合您的具体情况评估。",tag:"合规边界",use:"避免把通用能力讲成对个案的承诺。",example:"That would need to be assessed for your specific case and deployment model."},
  {en:"Let me connect you with the right specialist.",zh:"我来为您对接合适的专家。",tag:"转接专家",use:"专业问题不硬答，交给对应负责人。",example:"Let me connect you with the right specialist for a precise answer."},
  {en:"We can look at one concrete workflow first.",zh:"我们可以先看一个具体工作流。",tag:"方案推进",use:"把范围控制在可验证、可讨论的起点。",example:"We can look at one concrete workflow first, rather than trying to cover everything."},
  {en:"A sensible next step would be…",zh:"一个稳妥的下一步是……",tag:"收尾推进",use:"结束导览或演示时给对方明确但不过度承诺的下一步。",example:"A sensible next step would be a focused discussion with the relevant teams."},
  {en:"Would it be useful to continue the conversation after the visit?",zh:"参观结束后，是否方便继续交流？",tag:"收尾推进",use:"礼貌确认后续意愿。",example:"Would it be useful to continue the conversation after the visit?"},
  {en:"As promised, here is…",zh:"如约发送……",tag:"会后跟进",use:"用于兑现会中承诺的邮件或消息开头。",example:"As promised, here is the material we discussed during the visit."},
  {en:"Thank you for your time and thoughtful questions.",zh:"感谢您的时间和深入提问。",tag:"送别与跟进",use:"正式、得体地结束会面或邮件。",example:"Thank you for your time and thoughtful questions. We look forward to staying in touch."},
  {en:"Please feel free to ask questions at any point.",zh:"任何时候都欢迎您提问。",tag:"接待开场",use:"开始导览时降低提问门槛。",example:"Please feel free to ask questions at any point during the tour."},
  {en:"Let me pause here in case you have any questions.",zh:"我在这里暂停一下，看看您是否有问题。",tag:"导览节奏",use:"长段讲解后的主动停顿。",example:"Let me pause here in case you have any questions before we move on."},
  {en:"The information we can share today is…",zh:"今天我们可以分享的信息是……",tag:"信息边界",use:"在保密、未公开或范围受限时说明可讲部分。",example:"The information we can share today is the general approach and public materials."},
  {en:"We should avoid making a blanket statement.",zh:"我们应避免作一概而论的表述。",tag:"专业表达",use:"提醒自己或团队用条件化、准确的说法。",example:"We should avoid making a blanket statement without confirming the relevant conditions."},
  {en:"The answer depends on the customer scenario.",zh:"答案取决于客户场景。",tag:"专业表达",use:"面对“哪家更好”“是否一定适用”等问题时保留判断条件。",example:"The answer depends on the customer scenario, workflow and technical requirements."},
  {en:"So, to sum up,…",zh:"总结一下……",tag:"总结收口",use:"回收要点，并自然过渡到下一步。",example:"So, to sum up, we start with a defined problem and evaluate the result together."},
  {en:"I would be happy to clarify that.",zh:"我很愿意进一步说明这一点。",tag:"礼貌回应",use:"对方追问时的自然承接。",example:"I would be happy to clarify that with a more specific example."}
];
