/*
 * 每课短语包：只收录可独立记忆、可直接调用的中文 ↔ 英文短语。
 * 例句由 app.js 从本课已有的词汇、跟读、对话和应答材料中自动匹配，避免把整句说明误当短语卡。
 */
window.LESSON_PHRASES = {
  A1: [
    ["双引擎", "two engines"],
    ["消费互联网", "consumer internet"],
    ["产业互联网", "industrial internet"],
    ["业务单元 / 事业部", "business unit"],
    ["云与智慧产业事业群", "Cloud and Smart Industries Group"],
    ["服务企业与政府", "serve enterprises and governments"],
    ["用云和 AI 推动数字化", "go digital with cloud and AI"],
    ["从总体上看", "at a high level"],
    ["面向企业的一侧", "the enterprise-facing side"],
    ["明确的工作流", "a defined workflow"],
    ["客户服务场景", "a customer-service scenario"],
    ["改善最终结果", "improve the outcome"]
  ],
  A2: [
    ["月度订阅", "monthly subscription"],
    ["按量计费", "pay-as-you-go"],
    ["只为实际用量付费", "pay for what you use"],
    ["软件授权", "software licenses"],
    ["解决方案销售", "solution selling"],
    ["续约率", "renewal rate"],
    ["总拥有成本", "total cost of ownership"],
    ["价值主张", "value proposition"],
    ["前期硬件投入", "upfront hardware cost"],
    ["运营开支", "operating expenses"],
    ["资本开支", "capital expenditure"],
    ["灵活的运营开支", "flexible opex"],
    ["客户场景", "customer scenario"],
    ["明确的业务问题", "a clear business problem"],
    ["现有工作流", "the current workflow"],
    ["成功衡量指标", "success measures"],
    ["一长串产品清单", "a long product list"],
    ["可衡量的结果", "measurable outcomes"]
  ],
  A3: [
    ["云计算", "cloud computing"],
    ["像公用事业一样提供计算", "computing as a utility"],
    ["虚拟机", "virtual machine"],
    ["对象存储", "object storage"],
    ["本地部署服务器", "on-premise servers"],
    ["按需租用", "rent instead of buying"],
    ["高峰扩容", "scale up for peaks"],
    ["低谷缩容", "scale down for troughs"],
    ["计算工作负载", "computing workloads"],
    ["数据要求", "data requirements"],
    ["安全预期", "security expectations"],
    ["合适的技术架构", "an appropriate architecture"]
  ],
  A4: [
    ["事业群", "business group"],
    ["云与智慧产业事业群", "Cloud and Smart Industries Group"],
    ["社交与通讯事业群", "social and messaging group"],
    ["微信生态", "WeChat ecosystem"],
    ["矩阵式组织", "matrix organization"],
    ["汇报线", "reporting line"],
    ["对接合适的团队", "route you to the right team"],
    ["相关的业务或技术同事", "the relevant business or technical colleague"],
    ["企业云问题", "an enterprise-cloud question"],
    ["合作范围", "partnership scope"],
    ["业务目标", "business objective"],
    ["确认合适的负责人", "confirm the appropriate owner"]
  ],
  B1: [
    ["基础模型", "foundation model"],
    ["广泛数据", "broad data"],
    ["预训练", "pre-training"],
    ["通用能力", "general capability"],
    ["微调", "fine-tuning"],
    ["特定行业", "a specific industry"],
    ["下游任务", "downstream tasks"],
    ["模型参数", "model parameters"],
    ["多模态任务", "multimodal tasks"],
    ["开源版本", "open-source versions"],
    ["技术底座", "a general technical base"],
    ["业务问题", "business problem"]
  ],
  B2: [
    ["生成式 AI", "generative AI"],
    ["文本生成", "text generation"],
    ["图像生成", "image generation"],
    ["代码生成", "code generation"],
    ["清晰的提示词", "a clear prompt"],
    ["具体用例", "a concrete use case"],
    ["现有工作流", "your existing workflow"],
    ["业务场景", "a business setting"],
    ["首条回复", "a first response"],
    ["人工审核", "human review"],
    ["重复性环节", "a repetitive step"],
    ["适合辅助", "suitable for assistance"]
  ],
  B3: [
    ["AI 幻觉", "AI hallucination"],
    ["数据隐私", "data privacy"],
    ["负责任的 AI", "responsible AI"],
    ["人工在回路中", "human-in-the-loop"],
    ["经过批准的知识", "approved knowledge"],
    ["高影响决策", "high-impact decisions"],
    ["安全与公平", "safety and fairness"],
    ["人工审核", "human review"],
    ["部署模式", "deployment model"],
    ["适用法域", "jurisdiction"],
    ["安全与法务专家", "security and legal specialists"],
    ["可审计的流程", "auditable process"]
  ],
  B4: [
    ["自研基础模型", "self-developed foundation model"],
    ["AI 能力组合", "AI capability portfolio"],
    ["底层模型能力", "underlying model capability"],
    ["面向用户的应用", "user-facing application"],
    ["生成式助手", "generative assistant"],
    ["开源版本", "open-source versions"],
    ["云 API", "cloud API"],
    ["私有化部署", "private deployment"],
    ["技术要求", "technical requirements"],
    ["部署预期", "deployment expectations"],
    ["明确一个工作流", "define one workflow"],
    ["合适的选项", "the appropriate option"]
  ],
  B5: [
    ["企业知识库", "enterprise knowledge base"],
    ["经过批准的知识", "approved knowledge"],
    ["检索增强生成", "retrieval-augmented generation"],
    ["工具调用", "tool calling"],
    ["人工监督", "human oversight"],
    ["访问控制", "access control"],
    ["明确的工作流", "a defined workflow"],
    ["高影响决策", "high-impact decisions"],
    ["质量与安全标准", "quality and safety criteria"],
    ["审计要求", "audit requirements"],
    ["业务上下文", "business context"],
    ["已授权的工具", "approved tools"]
  ],
  C1: [
    ["用户为本", "user-oriented"],
    ["科技向善", "Tech for Good"],
    ["产品原则", "product principles"],
    ["社会价值", "social good"],
    ["ESG 指标", "ESG metrics"],
    ["碳中和目标", "carbon-neutrality goals"],
    ["AI 伦理治理", "AI ethics governance"],
    ["无障碍功能", "accessibility features"],
    ["社会责任", "social responsibility"],
    ["可衡量的行动", "measurable actions"],
    ["价值观指导决策", "values guide decisions"],
    ["负责任的介绍", "a responsible introduction"]
  ],
  C2: [
    ["客户故事", "customer story"],
    ["具体用例", "a concrete use case"],
    ["客户痛点", "customer pain point"],
    ["库存预测", "inventory forecasting"],
    ["减少缺货", "lower stock-outs"],
    ["预测性维护", "predictive maintenance"],
    ["医学影像", "medical imaging"],
    ["私域运营", "private-domain operations"],
    ["前后对比", "before-and-after"],
    ["可衡量的结果", "measurable result"],
    ["临床决策", "clinical decisions"],
    ["辅助临床工作", "support clinical work"]
  ],
  C3: [
    ["品牌差异化", "brand differentiation"],
    ["独特优势", "unique strengths"],
    ["生态连接能力", "ecosystem connectivity"],
    ["价值主张", "value proposition"],
    ["客户利益", "customer benefit"],
    ["行业解决方案", "industry solutions"],
    ["过往业绩", "track record"],
    ["客户场景", "customer scenario"],
    ["技术要求", "technical requirements"],
    ["成功衡量指标", "success measures"],
    ["实施条件", "implementation conditions"],
    ["避免宽泛主张", "avoid broad claims"]
  ],
  D1: [
    ["自我介绍", "self-introduction"],
    ["开放性问题", "open-ended question"],
    ["主要痛点", "main pain point"],
    ["相关场景", "a relevant scenario"],
    ["产品演示", "product demonstration"],
    ["深入交流", "a deeper discussion"],
    ["一分钟议程", "a one-minute agenda"],
    ["业务工作流", "business workflow"],
    ["聚焦一个主题", "keep it focused"],
    ["安排一次跟进", "schedule a follow-up"],
    ["了解对方需求", "learn their need"],
    ["提供帮助", "offer help"]
  ],
  D2: [
    ["视频会议", "video conferencing"],
    ["分布式团队", "distributed teams"],
    ["在线协作", "online collaboration"],
    ["快速入会", "fast join"],
    ["跨国通话", "cross-border calls"],
    ["企业版微信", "the enterprise version of WeChat"],
    ["内部团队", "internal teams"],
    ["外部客户", "external customers"],
    ["客户互动", "customer engagement"],
    ["一句话定位", "one-liner"],
    ["跨地域协作", "cross-location collaboration"],
    ["内外连接", "link internal teams and external customers"]
  ],
  D3: [
    ["这是个合理的问题", "that is a fair question"],
    ["这是个合理的顾虑", "that is a fair concern"],
    ["确认后回复您", "I will get back to you"],
    ["准确细节", "the exact detail"],
    ["不想凭猜测回答", "I do not want to guess"],
    ["跑题", "off-topic"],
    ["澄清范围", "clarify the scope"],
    ["相关团队", "the relevant team"],
    ["后续跟进", "follow up"],
    ["具体情况", "specific case"],
    ["确认信息", "verify the information"],
    ["回到正题", "get back on topic"]
  ],
  D4: [
    ["总结一下", "wrap up"],
    ["核心要点", "key takeaways"],
    ["行动号召", "call to action"],
    ["下一步", "next step"],
    ["安排一次跟进", "schedule a follow-up"],
    ["交换联系方式", "exchange contacts"],
    ["保持联系", "keep in touch"],
    ["碰一下进度", "touch base"],
    ["参观结束后", "after the visit"],
    ["聚焦讨论", "a focused discussion"],
    ["后续材料", "follow-up materials"],
    ["感谢您的时间", "thank you for your time"]
  ],
  E1: [
    ["这边请", "this way, please"],
    ["一直往前走", "go straight"],
    ["向左转", "turn left"],
    ["请跟我来", "follow me"],
    ["主大厅", "main lobby"],
    ["会议室", "meeting room"],
    ["访客证", "visitor badge"],
    ["接待台", "reception desk"],
    ["导览路线", "guided tour route"],
    ["下一个停留点", "the next stop"],
    ["抵达目的地", "reach the destination"],
    ["园区导览", "campus tour"]
  ],
  E2: [
    ["轻松聊天", "small talk"],
    ["安全话题", "safe topic"],
    ["商务旅行", "business travel"],
    ["第一次来访", "first visit"],
    ["当地天气", "local weather"],
    ["时差", "time difference"],
    ["舒适的节奏", "a comfortable pace"],
    ["共同话题", "common ground"],
    ["文化差异", "cultural differences"],
    ["礼貌地转场", "make a polite transition"],
    ["非正式开场", "an informal opening"],
    ["建立融洽关系", "build rapport"]
  ],
  E3: [
    ["读懂现场氛围", "read the room"],
    ["集合点", "meeting point"],
    ["技术问题", "technical issue"],
    ["保持冷静", "stay calm"],
    ["紧急出口", "emergency exit"],
    ["寻求协助", "ask for assistance"],
    ["急救", "first aid"],
    ["访客安全", "visitor safety"],
    ["变更计划", "change of plan"],
    ["及时通知所有人", "keep everyone informed"],
    ["处理突发情况", "handle an unexpected situation"],
    ["等待进一步指示", "wait for further instructions"]
  ],
  E4: [
    ["正在展出", "on display"],
    ["这展示了", "this demonstrates"],
    ["核心结论", "key takeaway"],
    ["最后总结", "in conclusion"],
    ["一路平安", "safe travels"],
    ["感谢来访", "thank you for visiting"],
    ["保持联系", "stay in touch"],
    ["未来合作", "future collaboration"],
    ["最后一站", "the final stop"],
    ["导览结束", "end of the tour"],
    ["重要信息", "the main message"],
    ["继续交流", "continue the conversation"]
  ],
  F1: [
    ["通俗语言", "plain language"],
    ["简而言之", "in a nutshell"],
    ["核心是", "the bottom line"],
    ["落实到实际", "in practical terms"],
    ["简单来说", "in simple terms"],
    ["关键点在于", "the key point is"],
    ["业务影响", "business impact"],
    ["技术细节", "technical detail"],
    ["清晰解释", "clear explanation"],
    ["客户能听懂的语言", "customer language"],
    ["避免行话", "avoid jargon"],
    ["复杂概念", "complex concept"]
  ],
  F2: [
    ["百分之", "per cent"],
    ["增长了", "increase by"],
    ["同比", "year on year"],
    ["上午", "a.m."],
    ["下午", "p.m."],
    ["人民币 / 美元", "RMB / USD"],
    ["数据点", "data point"],
    ["按计划进行", "on schedule"],
    ["目标日期", "target date"],
    ["当前数值", "current figure"],
    ["增长率", "growth rate"],
    ["预算范围", "budget range"]
  ],
  F3: [
    ["邮件主题", "subject line"],
    ["跟进邮件", "follow-up email"],
    ["行动项", "action item"],
    ["此致", "best regards"],
    ["您能否……", "could you please"],
    ["您是否介意……", "would you mind"],
    ["附件", "attached file"],
    ["会议纪要", "meeting notes"],
    ["下一步", "next steps"],
    ["日历邀请", "calendar invite"],
    ["邮件正文", "email body"],
    ["确认收到", "confirm receipt"]
  ],
  F4: [
    ["电话会议", "conference call"],
    ["加入会议", "join the call"],
    ["请稍等", "hold on"],
    ["行动项", "action item"],
    ["会议议程", "meeting agenda"],
    ["改期会议", "reschedule the meeting"],
    ["音频连接", "audio connection"],
    ["屏幕共享", "screen sharing"],
    ["会后跟进", "follow up after the call"],
    ["可用时间", "available time"],
    ["会议链接", "meeting link"],
    ["静音状态", "mute status"]
  ]
};
