/* 外宾模拟题库：每个问题与答案一一绑定。
 * 字段：q/zh=外宾提问；ref/refZh=本题标准示范；focus=本题回答必须覆盖的要点。
 * 不使用按数组位置拼接参考答案，避免追问与上一问错配。
 */
window.ROLE_TURNS = {
A1:[
{q:"Beyond WeChat, how would you describe Tencent to an international visitor?",zh:"除了微信，您会怎样向国际访客介绍腾讯？",ref:"At a high level, Tencent has consumer-facing businesses and also works with enterprises and public-sector customers through cloud, AI and industry solutions.",refZh:"总体来看，腾讯既有面向消费者的业务，也通过云、AI 和行业解决方案服务企业及公共部门客户。",focus:["consumer-facing","enterprises","cloud","AI"]},
{q:"Could you explain the enterprise-facing side in a little more detail?",zh:"能否再具体解释一下“面向企业”的部分？",ref:"The enterprise-facing side is about applying technology to defined industry workflows. A useful conversation starts with the customer's problem, the workflow to improve, and the outcome to measure.",refZh:"面向企业的一侧，是把技术用于明确的行业工作流。有价值的交流应从客户问题、需要改善的流程和需要衡量的结果开始。",focus:["industry workflows","customer's problem","outcome"]},
{q:"Could you give me one concrete example?",zh:"能给我一个具体例子吗？",ref:"For example, a retail team might examine one workflow such as inventory planning or customer service, then evaluate whether cloud and AI can help improve that specific process.",refZh:"例如，零售团队可以先审视库存规划或客服这样的一个工作流，再评估云和 AI 是否能改善这个具体流程。",focus:["retail","workflow","cloud","AI"]},
{q:"What would be a sensible next step after this introduction?",zh:"这段介绍之后，一个合理的下一步是什么？",ref:"A sensible next step would be to clarify the visitor's industry, current workflow and main objective, then involve the relevant business or technical colleague for a focused discussion.",refZh:"合理的下一步是明确访客所在行业、现有工作流和主要目标，再请对应业务或技术同事开展聚焦交流。",focus:["industry","workflow","objective","relevant"]}
],
A2:[
{q:"Is cloud always a large upfront investment?",zh:"云服务一定需要很大的前期投入吗？",ref:"Not necessarily. The cost model depends on the service and the workload. Rather than assume a price model, we should first understand the resources needed and the outcome the customer wants to achieve.",refZh:"不一定。成本模式取决于服务和工作负载。与其假设价格模式，不如先了解所需资源和客户希望实现的结果。",focus:["depends","service","workload","resources"]},
{q:"How is cloud consumption different from buying infrastructure?",zh:"使用云服务和购买基础设施有什么不同？",ref:"With cloud services, an organisation can consume computing or storage resources as needed. Buying infrastructure usually means owning and operating the physical equipment yourself. The exact commercial terms depend on the offering.",refZh:"使用云服务时，组织可按需使用计算或存储资源；购买基础设施通常意味着自行拥有并运营物理设备。具体商业条款取决于产品。",focus:["consume","resources","physical equipment","terms"]},
{q:"What should a customer compare before making a decision?",zh:"客户决策前应该比较什么？",ref:"They should compare the workload, implementation effort, operating responsibilities, security requirements and the outcome they expect to measure—not only the headline price.",refZh:"应比较工作负载、实施工作量、运维责任、安全要求和希望衡量的结果，而不只是表面价格。",focus:["workload","implementation","security","outcome"]},
{q:"What would be the next step for a serious discussion?",zh:"如果要认真讨论，下一步该做什么？",ref:"We would ask for a short description of the current workflow and success criteria, then arrange a discussion with the appropriate specialists to assess the fit.",refZh:"我们会请客户简要说明当前工作流和成功标准，再安排合适专家评估匹配度。",focus:["workflow","success criteria","specialists"]}
],
A3:[
{q:"What does cloud computing mean in practical terms?",zh:"云计算在实际应用中是什么意思？",ref:"In practical terms, cloud computing provides computing, storage and related services over a network, so an organisation can use resources without operating every physical server itself.",refZh:"在实际应用中，云计算通过网络提供计算、存储及相关服务，使组织无需自行运营每台物理服务器也能使用资源。",focus:["computing","storage","network","physical server"]},
{q:"Where do CVM and COS fit in?",zh:"CVM 和 COS 在其中分别是什么？",ref:"CVM refers to cloud virtual machines for computing workloads. COS is object storage for data such as files, images and videos.",refZh:"CVM 指用于计算工作负载的云服务器；COS 是用于文件、图片和视频等数据的对象存储。",focus:["CVM","computing","COS","storage"]},
{q:"If a team does not own the hardware, what does it still control?",zh:"如果团队不拥有硬件，仍然能控制什么？",ref:"The team still needs to manage its workload configuration, access permissions, data handling and operational choices. The appropriate controls depend on the architecture and service terms.",refZh:"团队仍需管理工作负载配置、访问权限、数据处理和运营选择。适用控制措施取决于架构和服务条款。",focus:["configuration","access","data","architecture"]},
{q:"How should a team begin an architecture discussion?",zh:"团队应该如何开始架构讨论？",ref:"Start with the workload, data requirements, security expectations and expected scale. Then the relevant technical team can discuss an appropriate architecture.",refZh:"先从工作负载、数据要求、安全预期和预估规模开始，再由相关技术团队讨论合适的架构。",focus:["workload","data","security","scale"]}
],
A4:[
{q:"Are WeChat and Tencent Cloud managed by the same team?",zh:"微信和腾讯云由同一个团队负责吗？",ref:"They are associated with different business groups and responsibilities. WeChat is associated with WXG, while cloud and industry-facing services are associated with CSIG.",refZh:"它们对应不同业务群和职责。微信相关业务对应 WXG，云及面向产业的服务对应 CSIG。",focus:["different","WXG","CSIG","cloud"]},
{q:"Who should I speak with about an enterprise-cloud question?",zh:"企业云问题应该找谁交流？",ref:"I would first understand the topic, then connect you with the relevant CSIG business or technical colleague. That is the best way to make sure the answer is precise.",refZh:"我会先了解议题，再为您对接 CSIG 对应的业务或技术同事，这样最能确保回答准确。",focus:["topic","CSIG","technical","precise"]},
{q:"What if the question involves more than one business group?",zh:"如果问题涉及不止一个业务群怎么办？",ref:"The right route depends on the partnership scope and business objective. Rather than guess the owner, I would clarify the objective first and then confirm the appropriate contacts.",refZh:"合适路径取决于合作范围和业务目标。与其猜测负责人，我会先明确目标，再确认合适联系人。",focus:["scope","objective","confirm","contacts"]},
{q:"What is the professional way to handle a question you cannot answer?",zh:"遇到无法回答的问题，专业做法是什么？",ref:"I would say what I can confirm, avoid guessing on details, and connect the visitor with the right specialist with a clear follow-up action.",refZh:"我会说明可以确认的部分，不对细节猜测，并以明确的后续动作对接合适专家。",focus:["confirm","avoid guessing","specialist","follow-up"]}
],
B1:[
{q:"What is a foundation model?",zh:"什么是基础模型？",ref:"A foundation model is trained on broad data so that it can support a range of downstream tasks. It is a general technical capability, not a finished solution for every business problem.",refZh:"基础模型在广泛数据上训练，可支持多类下游任务。它是通用技术能力，不是适用于所有业务问题的现成方案。",focus:["broad data","downstream tasks","general","not a finished solution"]},
{q:"What are the important limits of a foundation model?",zh:"基础模型有哪些重要局限？",ref:"A model can produce inaccurate or biased output, and its usefulness depends on the task, data, evaluation and human review around it. That is why deployment needs clear controls.",refZh:"模型可能产生不准确或有偏差的输出；其实用性取决于任务、数据、评估和人类审核。因此部署需要明确控制。",focus:["inaccurate","task","evaluation","human review"]},
{q:"Does a larger model automatically perform better?",zh:"模型越大就一定表现越好吗？",ref:"Not automatically. Performance depends on the task, data quality, evaluation method, deployment constraints and how the model is used in the workflow.",refZh:"不一定。表现取决于任务、数据质量、评估方法、部署约束以及模型如何进入工作流。",focus:["task","data quality","evaluation","workflow"]},
{q:"What should a business team ask first?",zh:"业务团队最该先问什么？",ref:"The first question is usually not which model is biggest. It is which task should be improved, what evidence is available, and how the result will be measured.",refZh:"第一个问题通常不是哪个模型最大，而是要改善哪个任务、有什么证据可用、如何衡量结果。",focus:["task","evidence","measured"]}
],
B2:[
{q:"What can generative AI do in a business workflow?",zh:"生成式 AI 能在业务工作流中做什么？",ref:"It can help generate or transform content such as text, images and code. The useful question is which step is repetitive, reviewable and suitable for assistance.",refZh:"它可以帮助生成或转换文本、图像和代码等内容。有价值的问题是哪一个步骤重复、可复核且适合获得辅助。",focus:["text","images","code","reviewable"]},
{q:"Could you give me one concrete example?",zh:"能给我一个具体例子吗？",ref:"For example, an assistant can draft a first response for a service agent. A person then reviews the content, adds context and decides whether to send it.",refZh:"例如，助手可为客服人员起草首条回复，再由人员审核内容、补充上下文并决定是否发送。",focus:["draft","service agent","reviews","decides"]},
{q:"How do you keep trust when AI helps create content?",zh:"AI 辅助创作内容时，如何保持可信度？",ref:"Trust comes from a clear process: define the approved use, verify important facts, keep appropriate human review, and make sure responsibility remains clear.",refZh:"可信度来自清晰流程：明确允许用途、核验重要事实、保留适当人工审核，并确保责任清晰。",focus:["process","verify","human review","responsibility"]},
{q:"What is a sensible first use case?",zh:"一个合理的首个用例是什么？",ref:"Start with one narrow workflow where the output can be reviewed easily and the result can be measured, rather than trying to automate everything at once.",refZh:"先从一个范围较窄、输出易于审核、结果可衡量的工作流开始，而不是一次自动化所有事情。",focus:["narrow workflow","reviewed","measured"]}
],
B3:[
{q:"Can an AI system produce information that is wrong?",zh:"AI 系统会产生错误信息吗？",ref:"Yes. A model can produce fluent content that is inaccurate, so important outputs should be checked against appropriate sources and reviewed by people.",refZh:"会。模型可能生成流畅但不准确的内容，因此重要输出应结合合适来源核验并由人员复核。",focus:["inaccurate","sources","reviewed"]},
{q:"How do you reduce that risk in practice?",zh:"实际中如何降低该风险？",ref:"A common approach is to ground answers in approved knowledge, define what the system may do, and keep people responsible for high-impact decisions.",refZh:"常见做法是让回答基于经过批准的知识、明确系统可执行范围，并让人员对高影响决策负责。",focus:["approved knowledge","define","people","decisions"]},
{q:"What should I say about data privacy?",zh:"我应该怎样说明数据隐私？",ref:"Data privacy needs to be assessed for the specific product, deployment model and jurisdiction. Detailed commitments should be confirmed with the relevant security and legal specialists.",refZh:"数据隐私需要结合具体产品、部署模式和适用法域评估。具体承诺应与相应安全和法务专家确认。",focus:["product","deployment","jurisdiction","specialists"]},
{q:"What should happen before a high-impact use case goes live?",zh:"高影响用例上线前应该做什么？",ref:"Before a high-impact use case goes live, the team should assess the workflow, data, risks, approval process and the human oversight required for that case.",refZh:"高影响用例上线前，团队应评估工作流、数据、风险、审批流程以及该场景所需的人类监督。",focus:["workflow","data","risks","oversight"]}
],
B4:[
{q:"Does Tencent develop its own foundation model?",zh:"腾讯是否自研基础大模型？",ref:"Tencent introduced the Hunyuan model in 2023. It is part of Tencent’s AI capability portfolio.",refZh:"腾讯在 2023 年推出混元大模型，它是腾讯 AI 能力组合的一部分。",focus:["Tencent","Hunyuan","2023","AI"]},
{q:"How should I understand the relationship between Hunyuan and Yuanbao?",zh:"应该如何理解混元和元宝的关系？",ref:"Hunyuan is the underlying model capability, while Yuanbao is an AI assistant product for users. They sit at different layers: model capability and user-facing application.",refZh:"混元是底层模型能力，元宝是面向用户的 AI 助手产品。两者处于不同层次：模型能力和用户应用。",focus:["Hunyuan","model","Yuanbao","application"]},
{q:"Which option is relevant for an organisation?",zh:"哪一种更适合一个组织？",ref:"That depends on the use case, technical requirements and deployment expectations. We should define one workflow first, then ask the relevant team to discuss the appropriate option.",refZh:"这取决于用例、技术要求和部署预期。应先明确一个工作流，再请相关团队讨论合适选项。",focus:["use case","technical","deployment","workflow"]},
{q:"What should I avoid saying in a product introduction?",zh:"产品介绍中应避免说什么？",ref:"Avoid making broad capability or deployment promises without confirming the current product documentation and the customer’s specific requirements.",refZh:"未经确认当前产品文档和客户具体要求时，应避免作出笼统的能力或部署承诺。",focus:["avoid","promises","documentation","requirements"]}
],
C1:[
{q:"What does “User-oriented, Tech for Good” mean in practice?",zh:"“用户为本，科技向善”在实践中意味着什么？",ref:"It is Tencent’s mission statement. In communication, it means explaining who technology serves, what value it creates and what responsibilities apply—not only what the technology can do.",refZh:"这是腾讯的使命表述。在沟通中，它意味着说明技术服务谁、创造何种价值和承担哪些责任，而不只讲技术能做什么。",focus:["mission","serves","value","responsibilities"]},
{q:"Could you make that more concrete?",zh:"能说得更具体一些吗？",ref:"For example, when introducing an AI capability, we should also explain the intended user scenario, the review process and the limits of what can be claimed.",refZh:"例如，介绍 AI 能力时，也应说明目标用户场景、审核流程以及可以作出承诺的边界。",focus:["AI","user scenario","review","limits"]},
{q:"Does that affect the way you present a product?",zh:"这会影响你们介绍产品的方式吗？",ref:"Yes. A responsible introduction is clear about benefits, evidence and limitations rather than relying on broad claims.",refZh:"会。负责任的介绍应清楚说明收益、依据和限制，而不是依赖笼统主张。",focus:["benefits","evidence","limitations"]},
{q:"What is one sentence I should remember?",zh:"我应该记住哪一句话？",ref:"Technology should be explained through the user value it creates and the responsibilities that come with its use.",refZh:"介绍技术时，应说明它创造的用户价值以及使用时伴随的责任。",focus:["user value","responsibilities"]}
],
C2:[
{q:"Can you share a case instead of a general product description?",zh:"能否分享一个案例，而不是泛泛介绍产品？",ref:"Certainly. A useful case story starts with the customer’s problem, then explains the workflow, the role of technology and the result that can be verified.",refZh:"当然。有价值的案例故事从客户问题开始，再说明工作流、技术角色和可核验结果。",focus:["problem","workflow","technology","verified"]},
{q:"How should I describe an AI-assisted healthcare example carefully?",zh:"我该如何谨慎介绍 AI 辅助医疗案例？",ref:"The careful description is that an AI-assisted capability can support clinical work. Diagnosis and clinical decisions remain with qualified healthcare professionals.",refZh:"严谨的说法是：AI 辅助能力可以支持临床工作；诊断和临床决策仍由合格医疗专业人员负责。",focus:["support","clinical","diagnosis","professionals"]},
{q:"What should a visitor listen for in a case story?",zh:"访客听案例时应关注什么？",ref:"Listen for the starting problem, the evidence behind the result and the conditions under which the example applies.",refZh:"应关注起始问题、结果背后的证据，以及案例适用的条件。",focus:["problem","evidence","conditions"]},
{q:"What is the next step if the case is relevant?",zh:"如果案例相关，下一步是什么？",ref:"The next step is to compare the visitor’s own workflow with the case conditions and ask the relevant specialists whether the approach is appropriate.",refZh:"下一步是将访客自身工作流与案例条件进行比较，并请相关专家判断该方法是否适合。",focus:["workflow","conditions","specialists"]}
],
C3:[
{q:"Why should a customer consider Tencent rather than another provider?",zh:"客户为什么要考虑腾讯而不是其他服务商？",ref:"The answer should begin with the customer scenario, not a broad comparison. We would first understand the workflow, technical requirements and success measures.",refZh:"回答应从客户场景开始，而不是泛泛比较。我们会先了解工作流、技术要求和成功衡量指标。",focus:["customer scenario","workflow","technical","success"]},
{q:"What strengths could be relevant?",zh:"哪些优势可能相关？",ref:"Depending on the scenario, the discussion may include cloud and AI capabilities, real-time communication, the WeChat ecosystem and experience in industry solutions. The relevance must be assessed case by case.",refZh:"视场景而定，讨论可能涉及云和 AI 能力、实时通信、微信生态和行业解决方案经验。相关性必须逐案评估。",focus:["scenario","cloud","WeChat","case"]},
{q:"How do we move from a claim to evidence?",zh:"怎样把主张变成证据？",ref:"Compare one concrete workflow, the implementation conditions and the outcome you want to measure. That is more useful than a broad statement about being better.",refZh:"比较一个具体工作流、实施条件和希望衡量的结果，比泛泛声称更好更有价值。",focus:["workflow","conditions","outcome"]},
{q:"What should I avoid in a competitive conversation?",zh:"竞争性对话中应该避免什么？",ref:"Avoid unverified comparisons or promises. If a detail depends on the customer’s context, say so and propose a focused assessment.",refZh:"应避免未经核验的比较或承诺。如果细节取决于客户背景，就应说明这一点并建议开展聚焦评估。",focus:["avoid","unverified","context","assessment"]}
],
D1:[
{q:"I am exploring technology for retail. Where should we begin?",zh:"我在了解零售技术，我们从哪里开始？",ref:"Before introducing a product, I would ask which part of the retail workflow matters most: store operations, customer engagement or data analysis.",refZh:"在介绍产品前，我会先了解零售工作流中最关注哪一部分：门店运营、客户互动还是数据分析。",focus:["retail","workflow","store","customer"]},
{q:"Why do you ask that before showing a demo?",zh:"为什么在演示前要问这个？",ref:"Because a short, relevant introduction is more useful than a generic demonstration. The answer helps us select one workflow and the right people for the conversation.",refZh:"因为简短且相关的介绍比泛泛演示更有价值。答案有助于选择一个工作流以及合适的交流人员。",focus:["relevant","generic","workflow","people"]},
{q:"What could you show me in one minute?",zh:"你能在一分钟内给我展示什么？",ref:"I can give a focused overview of one relevant scenario: the business problem, the workflow, the role of technology and the question we would evaluate next.",refZh:"我可以聚焦介绍一个相关场景：业务问题、工作流、技术角色以及下一步需要评估的问题。",focus:["problem","workflow","technology","evaluate"]},
{q:"What happens after the short introduction?",zh:"简短介绍之后会怎样？",ref:"If the scenario is relevant, we can decide whether a product demonstration or a deeper discussion with the appropriate team would be useful.",refZh:"如果场景相关，我们可以决定是否需要产品演示或与相应团队深入交流。",focus:["relevant","demonstration","discussion","team"]}
],
D2:[
{q:"What is Tencent Meeting used for?",zh:"腾讯会议主要用来做什么？",ref:"Tencent Meeting is a video-conferencing product. In a business setting, it supports online meetings and collaboration among participants in different locations.",refZh:"腾讯会议是一款视频会议产品，在业务场景中支持不同地点的参与者开展线上会议与协作。",focus:["video-conferencing","online meetings","collaboration"]},
{q:"How is WeCom different from WeChat?",zh:"企业微信和微信有什么不同？",ref:"WeCom is designed for organisational communication and customer connection, while WeChat is a consumer-facing communication product. Exact features should be confirmed against current product documentation.",refZh:"企业微信面向组织沟通和客户连接；微信是面向消费者的通信产品。具体功能应以当前产品文档为准。",focus:["WeCom","organisational","WeChat","documentation"]},
{q:"Which product should a company start with?",zh:"企业应该先从哪个产品开始？",ref:"That depends on the workflow. We should first clarify whether the priority is internal collaboration, customer connection or a combined process.",refZh:"这取决于工作流。应先明确优先事项是内部协作、客户连接还是两者结合的流程。",focus:["depends","workflow","internal","customer"]},
{q:"What is the safe way to discuss product features?",zh:"如何稳妥地讨论产品功能？",ref:"Describe the current use case and confirm the exact features, availability and integration details with the latest official product documentation or the relevant team.",refZh:"说明当前用例，并通过最新官方产品文档或相关团队确认具体功能、可用性和集成细节。",focus:["use case","features","availability","documentation"]}
],
D3:[
{q:"I am concerned about security in a cloud deployment.",zh:"我担心云部署的安全性。",ref:"That is a fair concern. Security should be discussed in relation to the specific product, deployment model, data type and regulatory requirements.",refZh:"这是合理的顾虑。安全应结合具体产品、部署模式、数据类型和监管要求来讨论。",focus:["security","product","deployment","data"]},
{q:"Can you guarantee a particular service level?",zh:"你能保证某个具体服务等级吗？",ref:"I do not want to guess on an SLA or make a blanket commitment. Let me confirm the applicable service terms with the relevant specialist.",refZh:"我不希望凭猜测回答 SLA，也不作一概承诺。我会与相关专家确认适用服务条款。",focus:["guess","SLA","commitment","specialist"]},
{q:"What can we discuss now?",zh:"那现在可以讨论什么？",ref:"We can clarify your workload, data sensitivity and access requirements. That will help the right team prepare a precise follow-up.",refZh:"我们可以先明确工作负载、数据敏感度和访问要求，这有助于对应团队准备准确后续答复。",focus:["workload","data","access","follow-up"]},
{q:"What should happen after this conversation?",zh:"这段交流后应该做什么？",ref:"The next step is to document the requirements and arrange a focused discussion with the appropriate security and technical specialists.",refZh:"下一步是记录需求，并安排与合适的安全和技术专家进行聚焦交流。",focus:["requirements","security","technical","specialists"]}
],
D4:[
{q:"What is a good way to close a product conversation?",zh:"怎样得体地结束一段产品交流？",ref:"First summarise the workflow and questions discussed. Then propose a focused next step that is appropriate for the visitor’s interest, rather than making a broad promise.",refZh:"先总结已讨论的工作流和问题，再根据访客兴趣提出聚焦下一步，而不是作出笼统承诺。",focus:["summarise","workflow","next step","promise"]},
{q:"What information would you need from us?",zh:"你们需要我们提供什么信息？",ref:"A short description of the current process, the outcome you want to improve and the people who should join the discussion would be a helpful start.",refZh:"简要说明当前流程、希望改善的结果以及应参与讨论的人员，就是很有帮助的起点。",focus:["current process","outcome","people"]},
{q:"How should you follow up after the visit?",zh:"参观结束后应该怎样跟进？",ref:"Send a concise summary of what was discussed, the material you agreed to share, and the next contact or action. Confirm details that require verification rather than guessing.",refZh:"发送简明总结，说明讨论内容、约定分享的材料以及下一联系人或行动。需要核实的细节应确认后再说。",focus:["summary","material","action","verification"]},
{q:"What is a useful phrase for proposing the next step?",zh:"提出下一步时什么表达有用？",ref:"A sensible next step would be a focused discussion with the relevant business and technical colleagues around your specific workflow.",refZh:"一个稳妥的下一步是围绕您的具体工作流，与相关业务和技术同事进行聚焦交流。",focus:["sensible","business","technical","workflow"]}
],
E1:[
{q:"Could you show me the plan for the visit?",zh:"能给我介绍一下今天的参观安排吗？",ref:"Certainly. We will begin with the showroom, then move to the meeting area. I will let you know before each transition and leave time for questions.",refZh:"当然。我们会先参观展厅，再前往会议区域。我会在每次转场前说明安排，并留出提问时间。",focus:["showroom","meeting","transition","questions"]},
{q:"How long is the walk?",zh:"步行大概多久？",ref:"It is a short walk. If you prefer, we can take the lift and adjust the pace at any point during the visit.",refZh:"距离不远。如果您愿意，我们可以乘电梯，并随时调整参观节奏。",focus:["short","lift","adjust","pace"]},
{q:"Where is the restroom?",zh:"洗手间在哪里？",ref:"It is just ahead on the right. Please take your time; I will wait here and then guide you to the next stop.",refZh:"就在前方右侧。请您慢慢来；我会在这里等候，再带您前往下一站。",focus:["ahead","right","wait","next stop"]},
{q:"What should you do before moving to the next stop?",zh:"前往下一站前应该做什么？",ref:"Briefly explain where you are going next, why the stop is relevant and invite questions before the transition.",refZh:"简要说明下一站去哪里、该站为何相关，并在转场前邀请提问。",focus:["where","relevant","questions","transition"]}
],
E2:[
{q:"It is my first time in Shenzhen and the flight was long.",zh:"这是我第一次来深圳，飞行时间很长。",ref:"Welcome to Shenzhen. I hope the journey was manageable. Before we begin, would you prefer some water or a short moment to settle in?",refZh:"欢迎来到深圳。希望旅程还算顺利。开始前，您想要一些水，还是先稍作休息？",focus:["Welcome","journey","water","settle in"]},
{q:"Why is that a better opening than casual small talk?",zh:"为什么这比随意寒暄更好？",ref:"It acknowledges the visitor’s situation and gives a practical choice. That is more considerate and keeps the conversation focused on the visitor.",refZh:"它回应了访客的状态并提供实际选择，更体贴，也让对话聚焦在访客身上。",focus:["acknowledges","choice","considerate","visitor"]},
{q:"What if the visitor wants to begin immediately?",zh:"如果访客希望立即开始怎么办？",ref:"Of course. I would respect the schedule and say, “Certainly. I will introduce the first stop and keep the visit focused on your priorities.”",refZh:"当然。我会尊重日程并说：“当然。我会介绍第一站，并让参观聚焦于您的重点。”",focus:["respect","schedule","first stop","priorities"]},
{q:"How can you keep the schedule flexible?",zh:"如何让日程保持弹性？",ref:"Let the visitor know that they can ask to slow down, pause or adjust the order if needed, then confirm any change clearly with the relevant hosts.",refZh:"告知访客可以随时放慢、暂停或调整顺序，并与相关接待人员清楚确认任何变动。",focus:["slow down","pause","adjust","confirm"]}
],
E3:[
{q:"I may have missed part of the explanation. Could you recap the main point?",zh:"我可能漏听了一部分，能否概括一下重点？",ref:"Of course. The key point is how this capability supports a defined workflow; the details can be discussed with the specialist if they are relevant to your team.",refZh:"当然。核心在于这项能力如何支持明确工作流；如果细节与贵团队相关，我们可以请专家进一步讨论。",focus:["key point","workflow","details","specialist"]},
{q:"Could we pause for a few minutes first?",zh:"我们能否先暂停几分钟？",ref:"Certainly. We can pause in the lounge for five minutes, then decide together whether to continue or adjust the remaining schedule.",refZh:"当然。我们可以在休息区暂停五分钟，然后共同决定继续参观还是调整后续日程。",focus:["pause","lounge","continue","adjust"]},
{q:"What if a demonstration has a technical issue?",zh:"如果演示出现技术问题怎么办？",ref:"I would acknowledge the issue briefly, avoid speculating on the cause, switch to the agreed backup if available, and explain the next step clearly.",refZh:"我会简要说明问题，避免猜测原因，如有条件则切换到约定备选方案，并清楚说明下一步。",focus:["acknowledge","avoid","backup","next step"]},
{q:"How should you adapt the rest of the visit?",zh:"应该如何调整剩余参观？",ref:"Keep the next explanation shorter, leave more room for questions, and confirm whether the visitor would prefer to continue, pause or adjust the agenda.",refZh:"让下一段讲解更简短，留出更多提问时间，并确认访客希望继续、暂停还是调整议程。",focus:["shorter","questions","continue","agenda"]}
],
E4:[
{q:"What are we looking at in this showcase?",zh:"这个展项展示的是什么？",ref:"At this stop, we are introducing Tencent Miying, an AI-assisted medical-imaging capability.",refZh:"这一站介绍的是腾讯觅影，一项 AI 辅助医疗影像能力。",focus:["Tencent Miying","AI-assisted","medical-imaging"]},
{q:"What is the appropriate way to describe its role?",zh:"应该如何恰当地说明它的作用？",ref:"The careful description is that it can support medical-imaging work. It does not replace qualified clinical judgment or the responsibilities of healthcare professionals.",refZh:"严谨的说法是：它可以支持医疗影像工作，但不替代合格临床人员的专业判断和职责。",focus:["support","medical-imaging","not replace","clinical"]},
{q:"What should a visitor look for in the demonstration?",zh:"访客在演示中应关注什么？",ref:"We can look at the workflow it is designed to support, the role of the clinician, and the evidence or evaluation relevant to that use case.",refZh:"可以关注它支持的工作流、临床人员角色，以及与该用例相关的证据或评估。",focus:["workflow","clinician","evidence","use case"]},
{q:"How do you transition to the next exhibit?",zh:"如何转场到下一个展项？",ref:"Next, we will move to a different industry scenario. Please feel free to ask questions as we walk over.",refZh:"接下来我们会前往另一个行业场景。步行过去时也欢迎您随时提问。",focus:["next","industry scenario","questions"]}
],
F1:[
{q:"How would you explain a foundation model simply?",zh:"你会怎样用简单方式解释基础模型？",ref:"A foundation model is a general model trained to handle a range of tasks. It still needs to be applied to a specific task and evaluated in context.",refZh:"基础模型是经过训练、可处理多类任务的通用模型。它仍需用于具体任务并结合场景评估。",focus:["general model","tasks","specific task","context"]},
{q:"So it is not a finished solution by itself?",zh:"所以它本身不是一个现成解决方案？",ref:"Exactly. The model is one capability layer. A useful solution also needs a clear workflow, appropriate data, human review and a way to measure results.",refZh:"正是。模型只是能力层之一。有用方案还需要明确工作流、合适数据、人类审核和衡量结果的方法。",focus:["capability","workflow","data","human review"]},
{q:"What is the one sentence I should remember?",zh:"最该记住的一句话是什么？",ref:"A foundation model is a general capability; business value comes from applying it responsibly to a defined workflow.",refZh:"基础模型是一种通用能力；业务价值来自把它负责任地应用到明确工作流。",focus:["general capability","business value","responsibly","workflow"]},
{q:"How do you keep a simple explanation accurate?",zh:"如何在简化解释时保持准确？",ref:"Use a plain definition first, keep the essential boundary, and avoid an analogy that changes the technical meaning or suggests capabilities that have not been confirmed.",refZh:"先使用朴素定义，保留必要边界，避免使用改变技术含义或暗示未确认能力的类比。",focus:["definition","boundary","avoid","confirmed"]}
],
F2:[
{q:"When was Tencent founded?",zh:"腾讯成立于哪一年？",ref:"Tencent was founded in 1998 and is headquartered in Shenzhen.",refZh:"腾讯成立于 1998 年，总部位于深圳。",focus:["1998","headquartered","Shenzhen"]},
{q:"How should I say a large user figure carefully?",zh:"大型用户数据应该怎样谨慎表达？",ref:"Use the latest official figure, name the metric clearly, and include the time period. For example: “According to the latest official disclosure, … monthly active users as of …”",refZh:"应使用最新官方数字，明确指标并说明时间范围。例如：“根据最新官方披露，截至某一时间，月活跃用户为……”",focus:["latest","official","metric","time period"]},
{q:"Should I quote a number from memory?",zh:"我应该凭记忆引用数字吗？",ref:"No. For figures such as users, revenue, availability or product metrics, verify the source and date before using them in an external conversation.",refZh:"不应该。对于用户数、收入、可用性或产品指标等数据，对外交流前应核验来源和日期。",focus:["verify","source","date","external"]},
{q:"How can I ask for time to verify a number?",zh:"我怎样请求时间核实一个数字？",ref:"I do not want to quote a figure from memory. Let me verify the latest official source and get back to you with the exact number.",refZh:"我不想凭记忆引用数字。我会核实最新官方来源后，再向您回复准确数字。",focus:["quote","memory","official","exact"]}
],
F3:[
{q:"Could you send a follow-up after the meeting?",zh:"会后能否发送跟进邮件？",ref:"Certainly. I will send a concise note that records what we discussed, the material we agreed to share, and the next step.",refZh:"当然。我会发送一封简明邮件，记录讨论内容、约定分享的材料以及下一步。",focus:["concise","discussed","material","next step"]},
{q:"What makes a clear email subject line?",zh:"怎样的邮件主题行才清晰？",ref:"Use a specific subject with the context and action, for example: “Follow-up: retail workflow discussion — materials and next steps.”",refZh:"使用包含背景和动作的具体主题，例如：“Follow-up: retail workflow discussion — materials and next steps.”",focus:["specific","context","action","Follow-up"]},
{q:"Should I promise an answer to every question immediately?",zh:"是否应承诺立刻回答每个问题？",ref:"No. If a detail needs verification, say so clearly, name the owner if appropriate, and give a realistic time for the follow-up.",refZh:"不应如此。如果细节需要核实，应明确说明，必要时指出负责人，并给出合理的跟进时间。",focus:["verification","owner","realistic","follow-up"]},
{q:"How should you close a professional follow-up email?",zh:"如何结束一封专业的跟进邮件？",ref:"Thank the visitor for the discussion, state the next action and timing, and invite them to correct or add anything important before the next conversation.",refZh:"感谢访客的交流，说明下一项行动及时间，并邀请对方在下一次交流前补充或更正重要事项。",focus:["thank","action","timing","invite"]}
],
B5:[
{q:"If we already have a foundation model, what else do we need for a real enterprise AI application?",zh:"如果已经有基础模型，做一个真正的企业 AI 应用还需要什么？",ref:"A foundation model is one capability layer. A real enterprise AI application also needs a defined workflow, approved knowledge, controlled tool access, human oversight and evaluation against clear criteria.",refZh:"基础模型只是能力层之一。真正的企业 AI 应用还需要明确工作流、经过批准的知识、受控的工具访问、人工监督以及依据明确标准的评估。",focus:["workflow","approved knowledge","tool access","human oversight"]},
{q:"What does an enterprise knowledge base do?",zh:"企业知识库起什么作用？",ref:"It provides the business context that the system is approved to retrieve and use. That makes the answer more traceable than relying only on a model’s general knowledge.",refZh:"它提供系统被批准检索和使用的业务上下文。这让回答比只依赖模型通用知识更可追溯。",focus:["business context","approved","retrieve","traceable"]},
{q:"Can an AI agent take actions on its own?",zh:"AI 智能体可以自行采取行动吗？",ref:"An agent can call approved tools within defined permissions, but important actions should remain subject to clear human approval and audit requirements.",refZh:"智能体可以在明确权限范围内调用经过批准的工具，但重要动作仍应接受清晰的人类审批和审计要求。",focus:["approved tools","permissions","human approval","audit"]},
{q:"Where should an enterprise start with AI adoption?",zh:"企业应该从哪里开始 AI 落地？",ref:"Start with one narrow workflow that has a clear problem, approved data, a review process and measurable success criteria. Evaluate the result before expanding.",refZh:"先从一个范围较窄的工作流开始，它应具备明确问题、经过批准的数据、审核流程和可衡量成功标准。扩展前先评估结果。",focus:["narrow workflow","approved data","review","measurable"]}
],
F4:[
{q:"I would like to arrange a discussion with the cloud team.",zh:"我想安排与云团队的交流。",ref:"Thank you for calling. To route this correctly, may I ask what topic you would like to discuss and who from your team should join?",refZh:"感谢来电。为便于正确对接，我想了解您希望讨论什么议题，以及贵方哪些人员应参与。",focus:["topic","team","join","route"]},
{q:"Why ask about the topic before proposing a time?",zh:"为什么在约时间前先问议题？",ref:"The topic helps us identify the relevant colleagues and prepare a useful agenda. Scheduling comes after we know who needs to be involved.",refZh:"议题有助于确定相关同事并准备有用议程。明确需要谁参与后再安排时间。",focus:["topic","relevant","agenda","involved"]},
{q:"What should you confirm before sending an invitation?",zh:"发送邀请前应确认什么？",ref:"Confirm the meeting format, time zone, attendees, topic and short agenda. Then send a calendar invitation with the practical joining details.",refZh:"确认会议形式、时区、参会人、议题和简短议程，再发送包含参会信息的日历邀请。",focus:["format","time zone","attendees","agenda"]},
{q:"How do you close the call professionally?",zh:"如何专业地结束电话？",ref:"Thank you. I will confirm the appropriate colleagues’ availability and send the invitation once the time and agenda are agreed.",refZh:"谢谢。我会确认相应同事的时间，在时间和议程达成一致后发送邀请。",focus:["confirm","availability","invitation","agenda"]}
]
};
